name: coomer-dl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - customtkinter
    - beautifulsoup4
    - urllib3
    - requests
    - pillow
    - psutil
    - markdown2
    - tkinterweb
    - cloudscraper
    - selenium
    - yt-dlp
    - gallery-dl
    - pytest
    - pytest-cov
    - flake8
